DEMO-342 (feat): Setup ngrx
RocketCommunicationsInc/Flight-Dynamics-Service pull request #15
Opened 2023-09-12 22:36 UTC by NicDominguez

**JIRA Ticket [DEMO-342](https://rocketcom.atlassian.net/browse/DEMO-342)**

## Brief Description

Installs NgRx to use for global stae management. Creates a featureGroup to hold satellies state. Also adds a selector to retrieve satellites state.

## Issues and/or Limitations

This is only the initial implmenation. Future construction of state to match correct data schema needed. I choose not to add ngrx/effects at this time to reduce complexity and ease the learning curve of this tool. 

## Final Checklist

- [X] Works in Chrome
- [X] Works in Firefox
- [X] Works in Safari
- [N/A] Handles responsiveness as required
- [N/A] Dark theme styles are correct
- [N/A] Light theme styles are correct

2023-09-13 14:38 UTC, nortonprojects approved these changes

2023-09-13 14:42 UTC, nortonprojects requested changes

2023-09-13 14:42 UTC, nortonprojects commented on src/app/store/app.selectors.ts
> +export const selectBookListPageViewModel = createSelector(
You don't need this at all, the `createFeature` function automatically creates selectors for state items (`selectSatellites`). Given the name, I'm guessing this was leftover from experimenting/learning

2023-09-13 14:43 UTC, nortonprojects commented on src/app/store/app.actions.ts
> +    'Satellites Requested': emptyProps(),
I'm also guessing you realize this, given your comment about `@ngrx/effects`, but this action doesn't currently do anything

2023-09-13 22:20 UTC, NicDominguez commented on src/app/store/app.selectors.ts
> +export const selectBookListPageViewModel = createSelector(
I did see that createFeature exported the simple selectors but I did want to try and provide the team an example of how a selector would be written. I added another piece of state so that I could write a more functional example of a selector.

2023-09-13 22:22 UTC, NicDominguez commented on src/app/store/app.actions.ts
> +    'Satellites Requested': emptyProps(),
I had not realized it but I see that now. The past tense naming convention using request and retrieve played in my head like request/response so I was thinking we needed both. I removed it.

2023-09-14 18:24 UTC, nortonprojects approved these changes

2023-09-14 18:41 UTC, merged