WIP: DEMO-385 use state in output data display
RocketCommunicationsInc/Flight-Dynamics-Service pull request #47
Opened 2023-09-28 18:07 UTC by brikiernan

**JIRA Ticket [DEMO-385](https://rocketcom.atlassian.net/browse/DEMO-385)**

## Brief Description

WIP

## Issues and/or Limitations

## Final Checklist

- [ ] Works in Chrome
- [ ] Works in Firefox
- [ ] Works in Safari
- [ ] Handles responsiveness as required
- [ ] Dark theme styles are correct
- [ ] Light theme styles are correct

2023-09-28 22:38 UTC, NicDominguez requested changes
Just a couple small clean up and formatting changes.

2023-09-28 22:38 UTC, NicDominguez commented on src/app/mock-data/generate-data.ts
> +  return ~~(Math.pow(10, precision) * num) / Math.pow(10, precision);
There is actually a prototype method on Number called toPrecision that does what you are trying to do without using exponents. Please use that instead.

2023-09-28 22:38 UTC, NicDominguez commented on src/app/main/output-data-display/output-data-display.service.ts
> +          property: key,
The Orbit Properties (i.e. keys) are in camel-case and sometimes abbreviated. Please format them to be their title case full names.

2023-09-28 22:38 UTC, NicDominguez commented on src/app/main/output-data-display/output-data-display.service.ts
> +      // prettier-ignore
please remove the formatting ignore

2023-09-29 14:22 UTC, brikiernan commented on src/app/main/output-data-display/output-data-display.service.ts
> +          property: key,
Took care of the title case part, not sure which ones are abbreviated and what the full names would be. May need a little assistance on that part, please.

2023-09-29 15:21 UTC, NicDominguez approved these changes

2023-09-29 15:21 UTC, merged