Km.demo 383 396 display and state spacecraft status
RocketCommunicationsInc/Flight-Dynamics-Service pull request #49
Opened 2023-09-28 19:24 UTC by kiley-mitti

**JIRA Ticket [Jira Issue Key](ticketURL)**

## Brief Description

## Issues and/or Limitations

## Final Checklist

- [ ] Works in Chrome
- [ ] Works in Firefox
- [ ] Works in Safari
- [ ] Handles responsiveness as required
- [ ] Dark theme styles are correct
- [ ] Light theme styles are correct

2023-09-28 20:16 UTC, brikiernan reviewed
Looks good 👍

2023-09-28 20:31 UTC, brikiernan commented on src/app/shared/units/unit-selector.component.css
> +  line-height: 0;
@kiley-mitti I find myself having to do this same type of thing you are doing here to get an icon aligned correctly when used as a trigger in a pop up. Can this be updated in Astro?

2023-09-28 22:06 UTC, NicDominguez requested changes
You had some overlap with Maria, please resolve the merge conflicts. The generated scenario names also need to be updated to the three in the figma file.

2023-09-29 15:08 UTC, kiley-mitti commented on src/app/shared/units/unit-selector.component.css
> +  line-height: 0;
I want to say yes but I'm thinking the answer is no because the moment anyone uses something with words in the popup trigger part having a set line height of 0 is going to mess them up. if :has() were something I could use (*shakes fist at Firefox*) might be able to do a ::has(rux-icon[slot=trigger]) or something to manage this use case. I can look into it though. maybe something I'm overlooking.

2023-09-29 15:35 UTC, kiley-mitti commented
@NicDominguez All set! While I was changing the scenario names I realized that adding a space made them ugly in the route so I added a little code to replace spaces with dashes in the guard and the scenarios library routing.
Then I realized that the spacecraft names are meant to have a space rather than a dash so I gave them the same treatment. Let me know if that's too much. :)

2023-09-29 15:59 UTC, NicDominguez approved these changes

2023-09-29 16:00 UTC, merged