Km.demo 403 track file utility add state
RocketCommunicationsInc/Flight-Dynamics-Service pull request #56
Opened 2023-09-29 21:03 UTC by kiley-mitti

[DEMO-403](https://rocketcom.atlassian.net/browse/DEMO-403)

## Brief Description

IN PROGRESS

## Issues and/or Limitations

## Final Checklist

- [ ] Works in Chrome
- [ ] Works in Firefox
- [ ] Works in Safari
- [ ] Handles responsiveness as required
- [ ] Dark theme styles are correct
- [ ] Light theme styles are correct

2023-10-02 21:39 UTC, brikiernan reviewed
@kiley-mitti there is a [table-service](https://github.com/RocketCommunicationsInc/Flight-Dynamics-Service/blob/main/src/app/shared/table.service.ts) which can handle all the sorting and selecting for this component. There are a couple of examples of it being used in the app. I'd be happy to connect with you in the morning to go over it a bit if you'd like.

2023-10-02 22:05 UTC, NicDominguez requested changes
I believe its worth implementing the table service for this to clean up streamline the app. I just merged an example in the propagator utility and Brian has one in the solution table. Please connect with Brian if you need assistance implementing it. Its a little complex to work with but it will clean up the component a bunch.

2023-10-04 14:55 UTC, kiley-mitti commented
Added the table service with a little extension of my own to handle filtering the track files. Also did a lot of selector cleanup and paring down subscriptions. Added the destroy method of subscription cleanup that Jacob recommended

2023-10-04 15:52 UTC, NicDominguez approved these changes

2023-10-04 15:52 UTC, merged