DEMO 326 (Feat): Add state to input panel
RocketCommunicationsInc/Flight-Dynamics-Service pull request #59
Opened 2023-10-02 17:41 UTC by FMorrison87

**JIRA Ticket [Jira Issue Key](ticketURL)**

## Brief Description

This PR pulls in state data and populates the form in the input data panel. The database file when selected display all possible trackfiles for the selected spacecraft. On selection, the trackfileId is sent back via store dispatch and then all trakfile values in the form should update according to trackfile state.

This PR includes a new custom selector to get the all track files on a spacecraft as an array of trackfile objects.

## Issues and/or Limitations

I'm not 100% sure that the values being passed into the form are correct as the names don't match 1:1 with what's in the wireframe. The dropdown on the file selector also needs some massaging as it still has the pointing caret (it's a rux-pop-up).

## Final Checklist

- [ ] Works in Chrome
- [ ] Works in Firefox
- [ ] Works in Safari
- [ ] Handles responsiveness as required
- [ ] Dark theme styles are correct
- [ ] Light theme styles are correct

2023-10-02 21:56 UTC, NicDominguez commented on src/app/main/inputs-outputs/inputs/inputs.component.ts
> +      filter((val) => val !== null)
This was the pattern I was looking for. I didn't realize you could use select inside a pipe.

2023-10-03 15:01 UTC, Paterma approved these changes

2023-10-03 15:56 UTC, NicDominguez requested changes

2023-10-03 15:56 UTC, NicDominguez commented on src/app/main/inputs-outputs/inputs/inputs.component.ts
> +          trackFileId: this.currentTrackFileId!,
This trackFileId is not necessary sense processedTrackFile has refId attached

2023-10-03 15:56 UTC, NicDominguez commented on src/app/core/scenario-library/scenario-library.component.ts
> +    );
Please change to new pattern

2023-10-03 15:56 UTC, NicDominguez commented on src/app/core/scenario-library/scenario-library.component.ts
>    }
Please change to new pattern

2023-10-03 15:56 UTC, NicDominguez commented on src/app/core/scenario-library/scenario-library.component.ts
> +      )
Check with Jacob to see if using Object.values(scenarioEntity) is doable

2023-10-03 15:56 UTC, NicDominguez commented on src/app/+state/app.selectors.ts
> +);
Possibly remove

2023-10-03 15:56 UTC, NicDominguez commented on src/app/+state/app.selectors.ts
> +);
Possibly remove

2023-10-03 16:32 UTC, FMorrison87 commented on src/app/core/scenario-library/scenario-library.component.ts
> +    );
Most of this has been removed now.

2023-10-03 16:32 UTC, FMorrison87 commented on src/app/core/scenario-library/scenario-library.component.ts
>    }
This was removed.

2023-10-03 16:35 UTC, FMorrison87 commented on src/app/main/inputs-outputs/inputs/inputs.component.ts
> +          trackFileId: this.currentTrackFileId!,
all set

2023-10-03 16:35 UTC, FMorrison87 commented on src/app/mock-data/generate-data.ts
> +  trackFileId: string | null
I fixed this too, took out the null

2023-10-03 16:36 UTC, FMorrison87 commented on src/app/types/data.types.ts
> +  trackFileRefId: string | null;
I removed the null

2023-10-03 16:58 UTC, NicDominguez approved these changes

2023-10-03 16:58 UTC, merged