DEMO 324 (feat): create scenarios library panel
RocketCommunicationsInc/Flight-Dynamics-Service pull request #7
Opened 2023-09-11 21:51 UTC by micahjones13

https://rocketcom.atlassian.net/browse/DEMO-324

## Brief Description
Created the Scenarios Library panel according to specs. 
This component listens to the `ruxtreenodeselected` event and, if it's a node (not a parent), stores that element in the `selectedCraft` signal. This means that other components will have access to that `selectedCraft`. 

## Issues and/or Limitations
I did have a question on what exactly we wanted to store in the `selectedCraft` signal. Right now it's the `rux-tree-node` element that was selected, but I could imagine that could change to a certain ID. I'll point to the instance in the file.

## Final Checklist

- [x] Works in Chrome
- [x] Works in Firefox
- [x] Works in Safari
- [ ] Handles responsiveness as required
- [ ] Dark theme styles are correct
- [ ] Light theme styles are correct

2023-09-11 21:53 UTC, micahjones13 commented on src/app/scenario-library/scenario-library.component.ts
> +  ];
Do we want a separate place for dummy data, or is inside the component fine for now?

2023-09-11 21:53 UTC, micahjones13 commented on src/app/scenario-library/scenario-library.component.ts
> +    if (el.slot === 'node') this.selectedCraft.set(el);
Sets the signal to store the selected `rux-tree-node`. Here is where we could change what data it stores - be it the entire element or just an ID that will be added later.

2023-09-11 21:59 UTC, nortonprojects commented on src/app/scenario-library/scenario-library.component.html
> +    <rux-tree-node *ngFor="let parentNode of dummyScenariosData">
Add `(ruxtreenodeselected)="onNodeSelected($event)"`

2023-09-11 22:02 UTC, nortonprojects requested changes

2023-09-11 22:02 UTC, nortonprojects commented on src/app/scenario-library/scenario-library.component.ts
> +    if (el.slot === 'node') this.selectedCraft.set(el);
Instead of using a `@HostListener`, add an event listener to the actual `rux-tree-node` - `@HostListener` is for events on the component itself (in this case ScenarioLibraryComponent)

2023-09-11 22:03 UTC, Paterma commented on src/app/scenario-library/scenario-library.component.ts
> +  ];
I think for now it's fine 👍🏼

2023-09-11 22:05 UTC, Paterma reviewed
Pull from main to get the latest scaffolding changes 👍🏼 Looks good though!

2023-09-11 22:06 UTC, nortonprojects commented on src/app/scenario-library/scenario-library.component.ts
> +      this.toast.nativeElement.querySelector('rux-toast-stack');
If you change your `this.toast` to use a `@ViewChild` - ie 
```
  @ViewChild(RuxToastStack) toast: RuxToastStack;
  ```
  You can use the addToast method directly - `this.toast.addToast({...})`

2023-09-11 22:26 UTC, micahjones13 commented on src/app/scenario-library/scenario-library.component.ts
> +    if (el.slot === 'node') this.selectedCraft.set(el.textContent);
Used text content here under the assumption that the tree nodes will be filled with actual craft numbers/ID's.

2023-09-11 23:24 UTC, Paterma approved these changes

2023-09-12 00:56 UTC, NicDominguez requested changes
Just a small change. Will you grow the container body to take the full height of the grid area?

2023-09-12 15:34 UTC, nortonprojects approved these changes

2023-09-12 17:37 UTC, NicDominguez approved these changes

2023-09-12 17:37 UTC, merged