DEMO 426 track file service refactor
RocketCommunicationsInc/Flight-Dynamics-Service pull request #79
Opened 2023-10-11 19:14 UTC by kiley-mitti

[DEMO-426](https://rocketcom.atlassian.net/browse/DEMO-426)

## Brief Description

This refactors the tracking data utility components to use the tracking data utility service to handle their table state.  This is so that when you return to 'Select Files' the filter and selection state will be in the same condition it was in before. When a new satellite is selected the table data filtering and selection resets.

## Issues and/or Limitations

## Final Checklist

- [x] Works in Chrome
- [x] Works in Firefox
- [x] Works in Safari
- [x] Handles responsiveness as required
- [x] Dark theme styles are correct
- [x] Light theme styles are correct

2023-10-11 20:43 UTC, NicDominguez requested changes
Just one duplicate code section that I think is an error.

2023-10-11 20:43 UTC, NicDominguez commented on src/app/main/utility-components/track-data-utility/track-data/track-data-graph/track-data-graph.component.html
> +</ng-template>
Good call

2023-10-11 20:43 UTC, NicDominguez commented on src/app/main/utility-components/track-data-utility/track-data/track-data-graph/track-data-graph.component.ts
>        }
duplication mistake?

2023-10-11 20:47 UTC, NicDominguez requested changes
Looks like there might be a styling error with the edit track file container. 
![image](https://github.com/RocketCommunicationsInc/Flight-Dynamics-Service/assets/8237598/8f263379-1d22-437c-b333-5619dfe7b40b)

2023-10-12 13:56 UTC, kiley-mitti commented on src/app/main/utility-components/track-data-utility/track-data/track-data-graph/track-data-graph.component.ts
>        }
yup! I find the merge editor in vscode to be a bit confusing. I'm getting better at dealing with it but... sometimes that happens :) Fixed!

2023-10-12 14:49 UTC, kiley-mitti commented
> Looks like there might be a styling error with the edit track file container.
> ![image](https://user-images.githubusercontent.com/8237598/274414253-8f263379-1d22-437c-b333-5619dfe7b40b.png)

Turns out this is a symptom of a larger issue. Adding the child tab component here completely changed when these components are created and destroyed and in doing so broke the chart updating. :) I'll be back with you when it is fixed.

2023-10-12 16:09 UTC, kiley-mitti commented
ok! assuming this compiles I do believe those bugs to be fixed :)

2023-10-12 16:27 UTC, FMorrison87 approved these changes

2023-10-12 16:27 UTC, FMorrison87 commented on src/app/main/utility-components/track-data-utility/track-files-data.service.ts
> +    destroyed = new Subject();
I actually don't think you need to add this if you're using `takeUntilDestroyed()`, same for the code in `ngOnDestroy()`

2023-10-12 16:27 UTC, FMorrison87 commented on src/app/main/utility-components/track-data-utility/track-files-data.service.ts
> +    destroyed = new Subject();
https://indepth.dev/posts/1518/takeuntildestroy-in-angular-v16

2023-10-12 17:06 UTC, NicDominguez approved these changes

2023-10-12 17:07 UTC, merged