feat: update unit conversions
RocketCommunicationsInc/Flight-Dynamics-Service pull request #80
Opened 2023-10-12 17:28 UTC by micahjones13

https://rocketcom.atlassian.net/browse/DEMO-421

## Brief Description

This PR updates and adds to the unit conversions for orbit properties. The selectable units for each property are now filtered based on the property. For example, you can't measure apogee in degrees. 
Adds time units (seconds, minutes, hours, days) for the period property. 
Adds mass (kg) unit. 
Adds a basic `num` unit that's used for eccentricity, since [eccentricity doesn't have units](https://nssdc.gsfc.nasa.gov/planetary/factsheet/planetfact_notes.html#:~:text=There%20are%20no%20units%20for%20eccentricity.). 

## Issues and/or Limitations

## Final Checklist

- [x] Works in Chrome
- [x] Works in Firefox
- [x] Works in Safari
- [ ] Handles responsiveness as required
- [ ] Dark theme styles are correct
- [ ] Light theme styles are correct

2023-10-12 19:33 UTC, NicDominguez requested changes
Just some additions to which units are available. We should probably avoid showing a select with only one option if possible.

2023-10-12 19:33 UTC, NicDominguez commented on src/app/shared/units/units.model.ts
> +  raan: [degrees],
Degrees and radians are different units for the same measurement so anywhere you can see degrees you should be able to choose radians and vice versa unless you found otherwise for specific properties.

2023-10-12 19:33 UTC, NicDominguez commented on src/app/shared/units/units.model.ts
> +  mass: [mass],
lets switch this to kilograms and allow for changing to pounds

2023-10-13 16:02 UTC, micahjones13 commented
> Just some additions to which units are available. We should probably avoid showing a select with only one option if possible.

In order to do this, we'd have to not render a `rux-select` but build something that looks the same so it's consistent with the other select menu's. I feel that would then be confusing as you'd have what looks like a select menu but it doesn't open anything when clicked. 
Unless we don't care about that consistency (which is totally fine), I think keeping the look and functionality the same between the unit selects is the best course.

2023-10-13 17:07 UTC, NicDominguez commented
> h

Sorry I wasn't clear. I just mean add more options if they are at all related. Not to render something different if there is only one option.

2023-10-16 15:32 UTC, merged